import AnalysisDetails from "@/components/AnalysisDetails";
import DynamicChart, { ChartPayload } from "@/components/DynamicChart";
import QueryError from "@/components/QueryError";
import { Badge } from "@/components/ui/badge";
import { trpc } from "@/lib/trpc";
import { Clock3, Database, MessageSquareText, Timer } from "lucide-react";

const date = (value: string | Date) => new Date(value).toLocaleString(undefined, { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" });

export default function AnalysisHistory() {
  const history = trpc.analysis.list.useQuery({});
  return <div className="space-y-6"><div><p className="text-sm font-semibold text-white">Analysis History</p><p className="mt-1 text-sm text-slate-500">A persistent audit trail of questions, queries, tools, results, and response times.</p></div>{history.error && <QueryError message={history.error.message} onRetry={() => history.refetch()} />}{history.isLoading ? <div className="rounded-2xl border border-slate-800 p-8 text-sm text-slate-500">Loading analysis history…</div> : history.data?.length ? <div className="space-y-4">{history.data.map(run => <article className="rounded-2xl border border-slate-800 bg-slate-900/45 p-5" key={String(run.id)}><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2"><Badge className={run.status === "succeeded" ? "border-0 bg-emerald-400/10 text-emerald-200" : "border-0 bg-red-400/10 text-red-200"}>{String(run.status)}</Badge><span className="text-xs text-slate-600">Run #{String(run.id)}</span></div><h2 className="mt-3 text-lg font-semibold text-white">{String(run.question)}</h2></div><div className="flex flex-wrap gap-3 text-xs text-slate-500"><span className="flex items-center gap-1.5"><Clock3 className="h-3.5 w-3.5" />{date(run.createdAt as Date | string)}</span><span className="flex items-center gap-1.5"><Timer className="h-3.5 w-3.5" />{String(run.durationMs)} ms</span></div></div><p className="mt-4 whitespace-pre-wrap text-sm leading-7 text-slate-300">{String(run.answer)}</p>{Boolean(run.visualization) && <div className="mt-5 rounded-2xl border border-slate-800 bg-slate-950/35 p-4"><DynamicChart payload={run.visualization as ChartPayload} /></div>}<div className="mt-5"><AnalysisDetails details={run.analysisDetails as any} /></div></article>)}</div> : <div className="grid min-h-64 place-items-center rounded-3xl border border-dashed border-slate-800 bg-slate-900/30 text-center"><div><MessageSquareText className="mx-auto h-7 w-7 text-slate-600" /><p className="mt-3 font-medium text-slate-300">No analyses yet</p><p className="mt-2 text-sm text-slate-500">Your completed AI Analyst questions will be retained here.</p></div></div>}</div>;
}
