import DatasetUploader from "@/components/DatasetUploader";
import QueryError from "@/components/QueryError";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { AlertCircle, ChevronRight, Database, FileSpreadsheet, Loader2, TableProperties } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useLocation } from "wouter";

type Profile = { rowCount: number; columnCount: number; dataQualityScore: number; encoding: string; sourceFormat: string; dateRange: { min: string; max: string } | null; columns: Array<{ name: string; type: string; nonNullCount: number; missingCount: number; uniqueCount: number; sampleValues: string[]; numeric?: { min: number; max: number; mean: number; sum: number }; categories?: Array<{ value: string; count: number }> }>; preview: Array<Record<string, unknown>> };

const date = (value?: string | Date | null) => value ? new Date(value).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" }) : "—";

export default function DatasetExplorer() {
  const [, setLocation] = useLocation();
  const utils = trpc.useUtils();
  const datasets = trpc.datasets.list.useQuery();
  const [selectedId, setSelectedId] = useState<number | null>(null);
  useEffect(() => { if (!selectedId && datasets.data?.[0]) setSelectedId(datasets.data[0].id); }, [datasets.data, selectedId]);
  const selected = trpc.datasets.get.useQuery({ datasetId: selectedId || 1 }, { enabled: Boolean(selectedId) });
  const profile = selected.data?.profile as Profile | undefined;
  const columns = useMemo(() => profile?.columns || [], [profile]);
  const deleteDataset = trpc.datasets.delete.useMutation({ onSuccess: () => { utils.datasets.list.invalidate(); utils.overview.get.invalidate(); setSelectedId(null); } });
  return <div className="space-y-6">{datasets.error && <QueryError message={datasets.error.message} onRetry={() => datasets.refetch()} />}{selected.error && <QueryError message={selected.error.message} onRetry={() => selected.refetch()} />}<div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-sm font-semibold text-white">Dataset Explorer</p><p className="mt-1 text-sm text-slate-500">Inspect the schema, quality, preview rows, and field-level statistics before analysis.</p></div><div className="w-full max-w-xl"><DatasetUploader onUploaded={id => { utils.datasets.list.invalidate(); utils.overview.get.invalidate(); setSelectedId(id); }} /></div></div>
    {!datasets.isLoading && !datasets.data?.length ? <div className="grid min-h-72 place-items-center rounded-3xl border border-dashed border-slate-800 bg-slate-900/30 p-8 text-center"><div><FileSpreadsheet className="mx-auto h-7 w-7 text-slate-600" /><p className="mt-4 font-medium text-slate-300">No data source selected</p><p className="mt-2 text-sm text-slate-500">Upload a CSV/XLSX file or load the sample dataset from Overview.</p></div></div> : <div className="grid gap-6 xl:grid-cols-[290px_minmax(0,1fr)]"><aside className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900/45"><div className="border-b border-slate-800 p-4"><p className="text-sm font-semibold text-white">Data sources</p><p className="mt-1 text-xs text-slate-500">Private to your account</p></div><div>{datasets.data?.map(dataset => <button key={dataset.id} onClick={() => setSelectedId(dataset.id)} className={`w-full border-b border-slate-800/70 p-4 text-left transition-colors last:border-0 ${selectedId === dataset.id ? "bg-blue-500/10" : "hover:bg-slate-800/40"}`}><div className="flex items-start justify-between gap-2"><FileSpreadsheet className={`mt-0.5 h-4 w-4 ${selectedId === dataset.id ? "text-blue-300" : "text-slate-500"}`} /><Badge variant="outline" className="border-slate-700 text-[10px] text-slate-400">{dataset.sourceKind}</Badge></div><p className="mt-3 truncate text-sm font-medium text-slate-200">{dataset.name}</p><p className="mt-1 text-xs text-slate-500">{dataset.rowCount.toLocaleString()} rows</p></button>)}</div></aside>
      <div className="space-y-5">{selected.isLoading ? <div className="grid h-72 place-items-center rounded-2xl border border-slate-800"><Loader2 className="h-5 w-5 animate-spin text-blue-300" /></div> : selected.data && profile ? <><section className="rounded-2xl border border-slate-800 bg-slate-900/45 p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><div className="flex items-center gap-2"><Database className="h-4 w-4 text-cyan-300" /><h2 className="text-xl font-semibold text-white">{selected.data.name}</h2></div><p className="mt-2 text-sm text-slate-500">{selected.data.originalFilename} · created {date(selected.data.createdAt)}</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => setLocation("/analyst")} className="border-slate-700 bg-slate-950/50 text-slate-200 hover:bg-slate-800 hover:text-white">Analyze data <ChevronRight className="ml-1 h-4 w-4" /></Button><Button variant="ghost" className="text-slate-500 hover:bg-red-400/10 hover:text-red-300" onClick={() => deleteDataset.mutate({ datasetId: selected.data!.id })}>Remove</Button></div></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Rows" value={profile.rowCount.toLocaleString()} /><Metric label="Columns" value={String(profile.columnCount)} /><Metric label="Data quality" value={`${profile.dataQualityScore}%`} /><Metric label="Date range" value={profile.dateRange ? `${date(profile.dateRange.min)} — ${date(profile.dateRange.max)}` : "Not detected"} /></div></section>
          <section className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900/45"><div className="border-b border-slate-800 px-5 py-4"><p className="flex items-center gap-2 text-sm font-semibold text-white"><TableProperties className="h-4 w-4 text-blue-300" />Schema & profiling</p><p className="mt-1 text-xs text-slate-500">Encoding: {profile.encoding} · format: {profile.sourceFormat}</p></div><div className="max-h-[430px] overflow-auto"><table className="w-full min-w-[760px] text-sm"><thead className="sticky top-0 bg-slate-900"><tr>{["Column", "Type", "Missing", "Unique", "Statistics / examples"].map(label => <th key={label} className="border-b border-slate-800 px-4 py-3 text-left text-xs font-semibold uppercase tracking-[0.12em] text-slate-500">{label}</th>)}</tr></thead><tbody>{columns.map(column => <tr key={column.name} className="border-b border-slate-800/70 last:border-0"><td className="px-4 py-3 font-medium text-slate-200">{column.name}</td><td className="px-4 py-3"><Badge className="border-0 bg-slate-800 text-slate-300">{column.type}</Badge></td><td className="px-4 py-3 text-slate-400">{column.missingCount} <span className="text-slate-600">/ {profile.rowCount}</span></td><td className="px-4 py-3 text-slate-400">{column.uniqueCount.toLocaleString()}</td><td className="px-4 py-3 text-xs text-slate-500">{column.numeric ? `min ${column.numeric.min.toFixed(2)} · avg ${column.numeric.mean.toFixed(2)} · max ${column.numeric.max.toFixed(2)}` : column.sampleValues.join(" · ") || "No values"}</td></tr>)}</tbody></table></div></section>
          <section className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900/45"><div className="border-b border-slate-800 px-5 py-4"><p className="text-sm font-semibold text-white">Preview rows</p><p className="mt-1 text-xs text-slate-500">First {Math.min(25, profile.preview.length)} parsed rows after validation and normalization.</p></div><div className="max-h-[420px] overflow-auto"><table className="w-full min-w-[760px] text-xs"><thead className="sticky top-0 bg-slate-900"><tr>{columns.map(column => <th className="border-b border-slate-800 px-3 py-3 text-left font-semibold text-slate-500" key={column.name}>{column.name}</th>)}</tr></thead><tbody>{profile.preview.map((row, index) => <tr className="border-b border-slate-800/60 last:border-0" key={index}>{columns.map(column => <td className="max-w-48 truncate px-3 py-2.5 text-slate-300" key={column.name}>{row[column.name] === null ? <span className="text-slate-600">null</span> : String(row[column.name])}</td>)}</tr>)}</tbody></table></div></section></> : <div className="flex items-center gap-3 rounded-2xl border border-amber-400/20 bg-amber-400/5 p-5 text-sm text-amber-100"><AlertCircle className="h-5 w-5" />Choose a dataset to inspect its profile.</div>}</div></div>}</div>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-slate-950/45 p-3"><p className="text-[11px] font-semibold uppercase tracking-[0.12em] text-slate-500">{label}</p><p className="mt-1.5 text-sm font-medium text-slate-200">{value}</p></div>; }
