import DatasetUploader from "@/components/DatasetUploader";
import QueryError from "@/components/QueryError";
import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowRight, Database, FileCheck2, Gauge, Loader2, MessageSquareText, Sparkles } from "lucide-react";
import { useLocation } from "wouter";
import { toast } from "sonner";

const dateText = (value?: Date | string | null) => value ? new Date(value).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" }) : "—";

export default function Overview() {
  const [, setLocation] = useLocation();
  const { user } = useAuth();
  const utils = trpc.useUtils();
  const overview = trpc.overview.get.useQuery();
  const datasets = trpc.datasets.list.useQuery();
  const health = trpc.overview.health.useQuery(undefined, { enabled: user?.role === "admin" });
  const sample = trpc.datasets.ensureSample.useMutation({ onSuccess: result => { utils.datasets.list.invalidate(); utils.overview.get.invalidate(); toast.success(result.existing ? "Sample workspace is already available." : "Sample sales dataset is ready to explore."); setLocation("/analyst"); }, onError: error => toast.error(error.message) });
  const stats = [
    { label: "Datasets", value: overview.data?.datasetCount ?? 0, icon: Database, note: "private data sources" },
    { label: "Analyses", value: overview.data?.analysisCount ?? 0, icon: MessageSquareText, note: "completed runs" },
    { label: "Data quality", value: overview.data?.latestDataset ? `${((overview.data.latestDataset.profile as any)?.dataQualityScore ?? "—")}%` : "—", icon: Gauge, note: "latest dataset score" },
  ];
  return <div className="space-y-7">{(overview.error || datasets.error) && <QueryError message={overview.error?.message || datasets.error?.message} onRetry={() => { overview.refetch(); datasets.refetch(); }} />}
    <section className="relative overflow-hidden rounded-3xl border border-slate-800 bg-gradient-to-br from-[#0e2740] via-[#0a1a2b] to-[#07111f] p-6 shadow-2xl shadow-blue-950/20 lg:p-9"><div className="absolute -right-24 -top-24 h-72 w-72 rounded-full bg-cyan-400/10 blur-3xl" /><div className="relative max-w-3xl"><div className="mb-5 flex w-fit items-center gap-2 rounded-full border border-blue-300/15 bg-blue-400/10 px-3 py-1 text-xs font-medium text-blue-200"><Sparkles className="h-3.5 w-3.5" />Autonomous data analysis, with evidence</div><h2 className="max-w-2xl text-3xl font-semibold tracking-tight text-white lg:text-4xl">Turn operational data into decisions you can inspect.</h2><p className="mt-4 max-w-2xl text-sm leading-6 text-slate-400">Upload a spreadsheet, ask a business question, and receive a safe SQL-backed response, focused visualization, and transparent analytical steps.</p><div className="mt-7 flex flex-wrap gap-3"><Button onClick={() => sample.mutate()} disabled={sample.isPending} className="bg-cyan-300 text-slate-950 hover:bg-cyan-200">{sample.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <FileCheck2 className="mr-2 h-4 w-4" />}Use sample sales data</Button><Button variant="outline" onClick={() => setLocation("/analyst")} className="border-slate-700 bg-slate-900/50 text-slate-200 hover:bg-slate-800 hover:text-white">Open AI Analyst <ArrowRight className="ml-2 h-4 w-4" /></Button></div></div></section>
    <section className="grid gap-4 md:grid-cols-3">{stats.map(stat => <div className="rounded-2xl border border-slate-800 bg-slate-900/45 p-5" key={stat.label}><div className="flex items-center justify-between"><p className="text-sm text-slate-400">{stat.label}</p><div className="grid h-9 w-9 place-items-center rounded-xl bg-slate-800 text-blue-300"><stat.icon className="h-4 w-4" /></div></div><p className="mt-4 text-3xl font-semibold text-white">{overview.isLoading ? "—" : stat.value}</p><p className="mt-1 text-xs text-slate-500">{stat.note}</p></div>)}</section>
    <section className="grid gap-6 xl:grid-cols-[1.45fr_1fr]"><div className="space-y-4"><div><p className="text-sm font-semibold text-white">Data sources</p><p className="mt-1 text-xs text-slate-500">Every analysis stays scoped to the selected dataset.</p></div><DatasetUploader onUploaded={datasetId => { utils.datasets.list.invalidate(); utils.overview.get.invalidate(); setLocation(`/datasets?dataset=${datasetId}`); }} /><div className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900/45"><div className="flex items-center justify-between border-b border-slate-800 px-5 py-4"><p className="text-sm font-semibold text-white">Available datasets</p><span className="text-xs text-slate-500">{datasets.data?.length ?? 0} sources</span></div>{datasets.isLoading ? <div className="p-6 text-sm text-slate-500">Loading sources…</div> : datasets.data?.length ? <div>{datasets.data.slice(0, 5).map(dataset => <button key={dataset.id} className="flex w-full items-center justify-between border-b border-slate-800/80 px-5 py-4 text-left last:border-0 hover:bg-slate-800/35" onClick={() => setLocation(`/datasets?dataset=${dataset.id}`)}><div><p className="text-sm font-medium text-slate-200">{dataset.name}</p><p className="mt-1 text-xs text-slate-500">{dataset.rowCount.toLocaleString()} rows · {dataset.columnCount} columns · {dateText(dataset.createdAt)}</p></div><ArrowRight className="h-4 w-4 text-slate-500" /></button>)}</div> : <div className="p-7 text-sm text-slate-500">No datasets yet. Use the sample sales data or upload a file to start.</div>}</div></div>
      <div className="rounded-2xl border border-slate-800 bg-slate-900/45 p-5"><p className="text-sm font-semibold text-white">Recent analyses</p><p className="mt-1 text-xs text-slate-500">Your last questions and results.</p><div className="mt-5 space-y-3">{overview.data?.recent?.length ? overview.data.recent.map(run => <button key={run.id} onClick={() => setLocation("/history")} className="w-full rounded-xl border border-slate-800 bg-slate-950/35 p-3 text-left transition-colors hover:border-slate-700"><p className="line-clamp-1 text-sm text-slate-200">{run.question}</p><p className="mt-2 text-xs text-slate-500">{dateText(run.createdAt)} · {run.durationMs} ms</p></button>) : <div className="rounded-xl border border-dashed border-slate-800 p-5 text-center text-sm text-slate-500">Your completed analyses will appear here.</div>}</div></div>
    </section>
    {user?.role === "admin" && <section className="rounded-2xl border border-slate-800 bg-slate-900/45 p-5"><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-semibold text-white">Operational health</p><p className="mt-1 text-xs text-slate-500">Administrator view · last 250 recorded events</p></div><p className="text-xs text-slate-600">{health.isLoading ? "Loading…" : `${health.data?.totalEvents ?? 0} events`}</p></div>{health.error ? <div className="mt-4 text-xs text-red-200">{health.error.message}</div> : <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><HealthMetric label="Successful analyses" value={health.data?.successfulAnalyses ?? 0} /><HealthMetric label="Average analysis" value={`${health.data?.averageDurationMs ?? 0} ms`} /><HealthMetric label="Average SQL" value={`${health.data?.averageSqlMs ?? 0} ms`} /><HealthMetric label="Failures" value={health.data?.failures ?? 0} danger={Boolean(health.data?.failures)} /><HealthMetric label="Retries" value={health.data?.retries ?? 0} /></div>}<div className="mt-4 flex flex-wrap gap-2">{Object.entries(health.data?.toolUsage ?? {}).map(([tool, count]) => <span key={tool} className="rounded-full bg-slate-950/55 px-2.5 py-1 text-[11px] text-slate-400">{tool}: {count}</span>)}</div></section>}
  </div>;
}

function HealthMetric({ label, value, danger = false }: { label: string; value: string | number; danger?: boolean }) { return <div className="rounded-xl bg-slate-950/45 p-3"><p className="text-[11px] font-semibold uppercase tracking-[0.12em] text-slate-500">{label}</p><p className={`mt-1.5 text-lg font-semibold ${danger ? "text-red-300" : "text-slate-200"}`}>{value}</p></div>; }
